In [120]:
day = "08"
file = f"/home/curt/Downloads/input{day}.txt"
#file = f"/home/curt/Documents/AoC/2022_AoC/input{day}_test.txt"

with open(file, 'r') as f:
    data = f.read().split("\n")
data.pop()

''

In [121]:
import numpy as np

In [122]:
tm = np.array([[int(t) for t in l] for l in data])
tm[:,0]
print(tm)
v = tm.shape[0]*2+tm.shape[1]*2-4
for y in range(1, tm.shape[0]-1):
    for x in range(1, tm.shape[1]-1):
        t, e, n, w, s = tm[y,x], tm[y, :x], tm[:y,x], tm[y,x+1:], tm[y+1:,x]
        v+=t>min(max(e), max(w), max(n), max(s))
print(v)

[[0 0 0 ... 2 2 2]
 [2 2 1 ... 2 2 0]
 [1 2 2 ... 2 0 2]
 ...
 [0 2 0 ... 0 1 1]
 [1 0 0 ... 0 1 0]
 [0 2 2 ... 1 2 1]]
1785


# Part Two

In [123]:
def tv(tree, row):
    for i, nt in enumerate(row, 1):
        if nt>=tree: return i
    return i

sceninc_scores = []
for y in range(1, tm.shape[0]-1):
    for x in range(1, tm.shape[1]-1):
        t, e, n, w, s = tm[y,x], tm[y, :x], tm[:y,x], tm[y,x+1:], tm[y+1:,x]
        sceninc_scores.append(tv(t, e[::-1])*tv(t, w)*tv(t, n[::-1])*tv(t, s))
print(max(sceninc_scores))

345168
